//fetch session actions
//for Saga
export const FETCH_USER_SESSION = "FETCH_USER_SESSION"
//for Redux
export const START_FETCH_USER_SESSION = "START_FETCH_USER_SESSION"
export const FETCH_USER_SESSION_SUCCESS = "FETCH_USER_SESSION_SUCCESS"
export const FETCH_USER_SESSION_FAILURE = "FETCH_USER_SESSION_FAILURE"